### ISSUE TITLE
Hebrew Words

### ISSUE THREAD

**Issue by elgringo18008** [Ordisoftware/Hebrew-Words#329]
Bonjour,
je n'ai aucune traduction qui s'affiche, est-ce normal ?

**Comment by Ordisoftware** [comment]
Bonjour, pouvez-vous détailler le problème en précisant l'élément concerné, et si possible ajouter une copie d'écran, svp ? Merci.

**Comment by elgringo18008** [comment]
Bonjour vous auriez pas un tuto en français pour expliquer comment se servir de l'appli? Car je ne sais pas si l'appli traduit automatiquement les mots hébreux au français ou bien si c'est nous qui devons créer la traduction. Dès que j'ouvre l'appli j'ai l'image ci joint, et après je ne sais pas quoi faire, cordialement 
![Capture d’écran 2023-09-24 073950](https://github.com/Ordisoftware/Hebrew-Words/assets/144712725/6207edc0-33f8-48b4-a5cc-5320f5e8b39b)

**Comment by Ordisoftware** [comment]
Bonjour,

Il n'y a pas de manuel pour le moment, je n'ai pas eu le temps.

_Hebrew Words est un logiciel qui aide à la traduction littérale mot-à-mot de la Torah et de la Bible hébraïque._

Vous devez donc faire le travail vous-même à l'aide des outils qui se trouvent principalement en cliquant droite ou gauche sur les numéros de versets et sur les mots hébreu. Vous pouvez paramétrer cela dans les paramètres via l'icône des roues crantées.

Le dictionnaire intégré des concordances  et l'outil d'aide à la traduction des versets ELS50 n'est pas encore disponible.

N'hésitez pas à poser toute question en cas de problème.

> ### Fonctionnalités
> 
> -   Traduction des versets mot-à-mot avec divers outils d'aide
> -   Menu contextuel sur un mot pour rechercher en ligne sa définition, voir les déjà traduit, rechercher dans la base de données ou étudier avec Hebrew Letters.
> -   Menu contextuel sur un verset pour le lire en ligne, gérer les signets, exporter ou importer.
> -   Recherche dans le Tanak des mots hébreux ou traduits avec filtres.
> -   Détermine les versets cachés de kabalah Pessah selon la séquence de lettres équidistantes de 50 pour Tav.
> -   Fenêtre montrant un tableau de livres modifiables.
> -   Fenêtre montrant un tableau des parashot avec descriptions.
> -   Fenêtre affichant un guide de grammaire.
> -   Fenêtre montrant quelques statistiques de Tanak.
> -   Export MS Word d'un livre, d'un chapitre ou d'un verset.
> -   Liens vers diverses ressources en ligne.
> -   Français, Anglais

Cordialement,
Olivier
